### ISSUE TITLE
Error when re-running "2. Intersect Shorelines And Baseline With Transects" tool

### ISSUE THREAD

**Issue by AlbertGallegoJimenez** [AlbertGallegoJimenez/shoreline-evolution-toolbox#1]
This tool creates two output files, i.e. both baseline and shoreline intersection features.
The problem occurs when these output files are rewritten with the same filenames as the first time the tool was run. The error is raised when calling the `arcpy.management.CreateFeatureclass()` function. This function is used to create an empty feature class to be filled with the calculated intersection points for both baselines and shorelines.

As you can see in the image below, the traceback error that ArcGIS identifies is related to a problem with invalid characters in the filename, which makes no sense as this error does not appear the first time you run the tool.

I've done several tests to pretend to fix this problem, but for some reason that escapes me, the error doesn't always appear, even when I try to reproduce the exact same process that previously gave me an error. I've coded something that should fix this, but it doesn't, the following snippet detects if the filename already exists and removes it before calling the `arcpy.management.CreateFeatureclass()` function.
`if arcpy.Exists(baseOutFeature):`
`    arcpy.Delete_management(baseOutFeature)`

For now, I have managed to solve the problem by doing the following:
- Restart ArcGIS Pro when the error occurs.
- Delete (if they still exist) the two baseline and shoreline intersection features in the default GDB where all the outputs are stored.
- Re-run the tool.

![image](https://github.com/AlbertGallegoJimenez/shoreline-evolution-toolbox/assets/91949040/2d9a9296-540d-449d-9e2c-6abc067b30ef)

**Comment by oc-gomesp** [comment]
The same error occurred to me when running step 2 and the solution proposed here worked for me.

**Comment by AlbertGallegoJimenez** [comment]
Dear all, please note that this bug has been fixed in v1.3.0. If you are using an older version of the toolbox, please update to a newer version.
