### ISSUE TITLE
Error when running "3. Perform The Analysis"

### ISSUE THREAD

**Issue by oc-gomesp** [AlbertGallegoJimenez/shoreline-evolution-toolbox#2]
The following error occured when running  module 3. Perform The Analysis and I am not sure how to fix it:

![error_module3](https://github.com/AlbertGallegoJimenez/shoreline-evolution-toolbox/assets/83269824/6e25f893-41c6-46d5-bb3e-d93bad3c2d10)

**Comment by AlbertGallegoJimenez** [comment]
I'm not quite sure where the error comes from.
One question, are there any transects that fall outside the shoreline area? I mean, are there any transects with 0 shoreline intersections?
If so, try deleting those transects and run the "2. Intersect Shorelines And Baseline With Transects" tool again.

**Comment by oc-gomesp** [comment]
Yes, there were 2 transects that don't touch the nay shorelines. 
I did what you recommended and it worked!
